### ISSUE TITLE
Debugger Problems

### ISSUE THREAD

**Issue by dj-on-github** [dj-on-github/py6502#6]
It looks like the recent changes broke the debugger.

$ python debugger.py load_store.asm
Traceback (most recent call last):
  File "debugger.py", line 602, in <module>
    s = sim6502(object_code,symbols=symbol_table)
  File "/Users/dj/Documents/src/py6502/src/sim6502.py", line 30, in __init__
    self.memory_map.InitializeMemory(address, object_code)
  File "/Users/dj/Documents/src/py6502/src/memory_map.py", line 51, in InitializeMemory
    raise ValueError
ValueError

memory_map.py at line 51 is checking that there are no out of range memory values (0-255), but the object_code object passed from sim6502.py contains uninitialized memory (-1) as it should.

Turning off that check we get.
$ python debugger.py load_store.asm
Traceback (most recent call last):
  File "debugger.py", line 605, in <module>
    dis = dis6502(s.object_code,symbols=symbol_table)
AttributeError: 'sim6502' object has no attribute 'object_code'
$

sim6502.py takes in object_code as a parameter but doesn't assign it to self.object_code.

Fixing that by having debugger.py refer to object_code rather than s.object_code we get..

A) The reset vector isn't followed. To reproduce
$ python debugger.py load_store.asm
Type 'R' to reset. Observe that the reset vector is 0x100
Type 's' to step one instruction, which should follow the reset vector. It does not.

B) It crashes when it reaches a real instruction
Keep typing 's' until you reach PC=0x100 and this happens..

$ python debugger.py load_store.asm
Traceback (most recent call last):
  File "debugger.py", line 608, in <module>
    d = dbg6502(object_code,symbol_table)
  File "debugger.py", line 485, in dbg6502
    draw_disassembly_inner_view(vptu_disassembly_inner,object_code)
  File "debugger.py", line 250, in draw_disassembly_inner_view
    vptu.addstr(x=0,y=i,thestring=linelist[i],bold=False)
  File "/Users/dj/Documents/src/py6502/src/termbox_util.py", line 224, in addstr
    self.tb.change_cell(x+i, y, ord(thestring[i]), self.fg,self.bg)
TypeError: ord() expected a character, but string of length 34 found

Which I don't understand yet. It's looks like termbox_util is being sent a list of strings from the debugger rather than a string.

**Comment by dj-on-github** [comment]
Added a log of what string was being passed to line 224 of termbox_util and got this.
$ tail py6502_debugger.log
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:           00ff 00       DW  $00
DEBUG:root:('start:     0100 a9 aa    lda  #$aa', 2)

That '2' shouldn't be there.

**Comment by dj-on-github** [comment]
Fixes were submitted.
